### ISSUE TITLE
license selection is broken

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/packaging-guide#17] opened 2021-05-19 11:36 UTC
If one runs
```python
pieceofcake gh:OpenAstronomy/packaging-guide ./output_directory
```
and chooses the default answer to every question, apart from choosing '1' for the license selection, you should get the BSD clause 3 license. `packagename/licenses/LICENSE.rst` and `README.rst` have the GNU GPL v3+ license selected however.

**Comment by saimn** [comment] 2022-03-09 13:27
Choosing the 5th option results in a crash here:
```
1 - BSD 3-Clause
2 - GNU GPL v3+
3 - Apache Software License 2.0
4 - BSD 2-Clause
5 - Other
> license [1]: 5
Traceback (most recent call last):
  File "/home/sconseil/.pyenv/versions/3.9.4/bin/pieceofcake", line 8, in <module>
    sys.exit(main())
  File "/home/sconseil/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sconseil/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sconseil/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sconseil/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sconseil/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pieceofcake/main.py", line 96, in main
    values[key] = value[click.prompt(BOLD + '> ' + prompt + END,
IndexError: list index out of range
```

**Comment by hamogu** [comment] 2022-08-17 15:22
Choosing option 2 gives you the Apache license. Maybe just an off-by-one error?

**Comment by Cadair** [comment] 2022-11-09 15:48
effective duplicate of #11

**Closed** 2022-11-09 15:48 UTC
